### ISSUE TITLE
take a look around and find something to fix that i missed

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/awesome-dev-stuff#27]
this website is mostly done. i have a list of knowtes, but want you to check it with a fresh eye and find something that can be improved. it can be really launched in 1-3 days

**Comment by vadim9999** [comment]
ok

**Comment by vadim9999** [comment]
@atherdon Have you deleted button summary from the navbar?

**Comment by vadim9999** [comment]
https://github.com/ChickenKyiv/awesome-dev-stuff/pull/28

**Comment by vadim9999** [comment]
@atherdon I have done improvement
