### ISSUE TITLE
add images to our sections

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/awesome-dev-stuff#4]
for now, we just need to display that images inside of our pages
https://github.com/GroceriStar/creative/tree/master/website-illustrations

**Comment by vadim9999** [comment]
@atherdon should I copy all images and past it in folder or insert in pages a link like on img?

**Comment by vadim9999** [comment]
In PR https://github.com/ChickenKyiv/awesome-dev-stuff/pull/5

**Comment by atherdon** [comment]
am I right - we made a major's changes here and it looks fine or what is not done in total?
