### ISSUE TITLE
simple task for Elnur #1 

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/awesome-dev-stuff#8]
your task will be: improve this file for now: 
https://github.com/ChickenKyiv/awesome-dev-stuff/blob/master/docs/github/cool-github-repositories.md

what do you need to do?

right now we have this structure: https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code

you need to format it to [https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code](This startup wants to disrupt education by paying you 10000 learn code)

**Comment by atherdon** [comment]
@elnur004

**Comment by elnur004** [comment]
Hi, Arthur!

to tell the truth, i can't understand this task.

you say: "right now we have this structure: https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code

you need to format it to [https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code](This startup wants to disrupt education by paying you 10000 learn code)"
may you explain this opinion please?

**Comment by atherdon** [comment]
our website will have a markdown format.
so your work will be to do from 
`https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code`
to 
`[https://www.goodnet.org/articles/this-startup-wants-to-disrupt-education-by-paying-you-10000-learn-code](This startup wants to disrupt education by paying you 10000 learn code)` 

actually i made some changes, so you'll need to add just a readable title - that goes between **[ ] **

more about markdown format: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links

**Comment by atherdon** [comment]
and don't worry if you don't understand task for the first times - communications is always important at dev teams

**Comment by atherdon** [comment]
if you want to do another page - just take a look at `docs` folder what can be improved and tomorrow when i'll wake up i'll prepare another task for you

**Comment by atherdon** [comment]
Amazed with your changes. merging your pull requests right now.
Nice work - you motivate me to speed up my part of work and try to publish our website today

**Comment by elnur004** [comment]
when i do my task successfully it also motivates and makes me an
enthusiasm. And i willing to do my best))

Thank you Arthur for support and encouragement!

**Comment by elnur004** [comment]
when i do my task successfully it also motivates and makes me an
enthusiasm. And i willing to do my best))

Thank you Arthur for support and encouragement!

And waiting for new tasks!

**Comment by atherdon** [comment]
Shall we continue with a similar task(i have some other repositories with
links)
Or I can find something else for you

>

**Comment by atherdon** [comment]
the quick task from another repository: https://github.com/GroceriStar/sd/issues/90
second task: https://github.com/GroceriStar/sd/issues/96

**Comment by elnur004** [comment]
i want to gain more experience and practice around javascript and deeply learn this language.
So i would like to do more tasks around javascript.

**Comment by atherdon** [comment]
cool. this is what i though too. will plan more new tasks for you in next week. 

will try with our team member to finish this website and try to present it to ProductHunt community today or tomorrow. You made great progress and speed up this launch

**Comment by elnur004** [comment]
great. this will be quite enjoyable!

**Comment by atherdon** [comment]
from mrketing side - it will bring some attention to us
from our side - it's a pretty useful set of links that i'm using frequently
and share with our team members.
with a good and easy table of contents it can be a great tool for mastering
skills

>

**Comment by atherdon** [comment]
closing this task
